# Generated by Django 5.1.1 on 2024-10-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acss_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student_id',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
