# Generated by Django 5.1.1 on 2024-10-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acss_app', '0002_remove_enrollment_student_id_enrollment_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_name',
            new_name='student',
        ),
    ]
